apiVersion: batch/v1
kind: Job
metadata:
  name: batch-bancario-job
spec:
  template:
    spec:
      hostAliases:
      - ip: "192.168.1.215"
        hostnames:
        - "oracle-db"
      containers:
        - name: simulacion-container
          image: simulacion-bancaria:local
          imagePullPolicy: Never
          # Esto sobrescribe el CMD del Dockerfile:
          args: ["META-INF/spring/batch/jobs/lox-job.xml", "LOXJ162-01-MX", "odate=20260706"]
      restartPolicy: Never